Diffusion Models - Live Coding Tutorial
url: https://www.youtube.com/watch?v=S_il77Ttrmg

In [11]:
"""
mean = sqrt(a_hat_t) * x_0)
variance = sqrt(1 - a_hat_t) * random_noise
"""
import torch

x0 = torch.randn(2, 3, 32, 32) 
betas = torch.tensor([0.05, 0.1, 0.15, 0.2, 0.25])
t = torch.tensor([1, 3])

# betas -> количество шума, которое применяется на каждом шаге процесса диффузии
# alphas -> 1 - betas -> количество информации об исходном изображении, сохраняемое после процесса диффузии

alphas = 1 - betas

alpha_hat = torch.cumprod(alphas, axis = 0)
print(alphas)
print(alpha_hat)
print(alpha_hat.size())
result = alpha_hat.gather(-1, t).reshape(-1, 1, 1, 1)
print(result)
print(result.size())

noise = torch.rand_like(x0)
mean = result.sqrt() * x0
variance = torch.sqrt(1 - result) * noise

x_t = mean + variance
x_t.size()

tensor([0.9500, 0.9000, 0.8500, 0.8000, 0.7500])
tensor([0.9500, 0.8550, 0.7268, 0.5814, 0.4360])
torch.Size([5])
tensor([[[[0.8550]]],


        [[[0.5814]]]])
torch.Size([2, 1, 1, 1])


torch.Size([2, 3, 32, 32])